# Generated by Django 4.1.4 on 2023-01-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Posted_by', models.TextField()),
                ('Proptype', models.TextField()),
                ('Link', models.TextField()),
                ('Owner', models.TextField()),
                ('Locality', models.TextField()),
                ('City', models.TextField()),
                ('Charges', models.TextField()),
                ('PG_for', models.TextField()),
                ('Description', models.TextField()),
            ],
        ),
    ]
